
#داله جلب البينات جدول الاصناف

GET http://192.168.1.110:8000/api/Get-categories
Accept: application/json

### داله لجلب المنتجات عند طريق الصنف

GET http://192.168.1.110:8000/api/Get-categories-prodect/2
Accept: application/json

### داله للبحث عن مزود عنط ريق اسمه
GET http://192.168.1.110:8000/api/Search_Manger/b

###
GET http://192.168.1.110:8000/api/Get-Request-Clinic/2
# Accept: application/json

### داله رفع طلب اضافه رصيد
POST http://192.168.1.110:8000/api/balance/5
Content-Type: application/json
Accept: application/json

{
    "totel_balance": 1500,
    "description": "  إيداع جديد عن طريق حواله رقمها 1155501"
}

# GET http://192.168.1.110:8000/api/get-data
# Accept: application/json