
#داله جلب البينات جدول الاصناف

# GET http://192.168.1.110:8000/api/Get-categories
# Accept: application/json

// داله لجلب المنتجات عند طريق الصنف
# GET http://192.168.1.110:8000/api/Get-categories-prodect/4
# Accept: application/json

# داله للبحث عن مزود عنط ريق اسمه
# GET http://192.168.1.110:8000/api/Search_Manger/عما
# Accept: application/json